# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_config.proto\x12\x05proto\" \n\x0fUserInforequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1b\n\rUserInfoReply\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x16\x41ppointmentInforequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\"\n\x14\x41ppointmentInfoReply\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x0c\x44\x65layedReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x07request\x18\x02 \x03(\x0b\x32\x16.proto.UserInforequest2\x8f\x01\n\x04User\x12\x38\n\x08UserInfo\x12\x16.proto.UserInforequest\x1a\x14.proto.UserInfoReply\x12M\n\x0f\x41ppointmentInfo\x12\x1d.proto.AppointmentInforequest\x1a\x1b.proto.AppointmentInfoReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFOREQUEST._serialized_start=28
  _USERINFOREQUEST._serialized_end=60
  _USERINFOREPLY._serialized_start=62
  _USERINFOREPLY._serialized_end=89
  _APPOINTMENTINFOREQUEST._serialized_start=91
  _APPOINTMENTINFOREQUEST._serialized_end=130
  _APPOINTMENTINFOREPLY._serialized_start=132
  _APPOINTMENTINFOREPLY._serialized_end=166
  _DELAYEDREPLY._serialized_start=168
  _DELAYEDREPLY._serialized_end=235
  _USER._serialized_start=238
  _USER._serialized_end=381
# @@protoc_insertion_point(module_scope)
