# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_config_pb2 as grpc__config__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserInfo = channel.unary_unary(
                '/proto.User/UserInfo',
                request_serializer=grpc__config__pb2.UserInforequest.SerializeToString,
                response_deserializer=grpc__config__pb2.UserInfoReply.FromString,
                )
        self.AppointmentInfo = channel.unary_unary(
                '/proto.User/AppointmentInfo',
                request_serializer=grpc__config__pb2.AppointmentInforequest.SerializeToString,
                response_deserializer=grpc__config__pb2.AppointmentInfoReply.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppointmentInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UserInfo,
                    request_deserializer=grpc__config__pb2.UserInforequest.FromString,
                    response_serializer=grpc__config__pb2.UserInfoReply.SerializeToString,
            ),
            'AppointmentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AppointmentInfo,
                    request_deserializer=grpc__config__pb2.AppointmentInforequest.FromString,
                    response_serializer=grpc__config__pb2.AppointmentInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.User/UserInfo',
            grpc__config__pb2.UserInforequest.SerializeToString,
            grpc__config__pb2.UserInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppointmentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.User/AppointmentInfo',
            grpc__config__pb2.AppointmentInforequest.SerializeToString,
            grpc__config__pb2.AppointmentInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
