# Generated by Django 4.1.5 on 2023-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
